import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, ArrowRight, BookOpen, CalendarDays, Filter } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import AuthDialog from "@/components/AuthDialog";
import { supabase } from "@/lib/supabase";
import { trpc } from "@/lib/trpc";

type HistoryItem = { id: string; original_text: string | null; final_score: number; created_at: string; source_type: string; result: unknown };

export default function Corrections() {
  const [authUser, setAuthUser] = useState<import("@supabase/supabase-js").User | null>(null);
  const [filter, setFilter] = useState<"recent" | "highest" | "lowest" | "oldest">("recent");
  const historyQuery = trpc.correction.history.useQuery(undefined, { enabled: Boolean(authUser), retry: false });
  useEffect(() => { if (!supabase) return; void supabase.auth.getUser().then(({ data }) => setAuthUser(data.user)); }, []);
  const items = useMemo(() => { const list = [...(historyQuery.data ?? [])] as HistoryItem[]; if (filter === "highest") return list.sort((a, b) => b.final_score - a.final_score); if (filter === "lowest") return list.sort((a, b) => a.final_score - b.final_score); if (filter === "oldest") return list.reverse(); return list; }, [filter, historyQuery.data]);
  if (!authUser) return <main className="flex min-h-screen items-center justify-center bg-[#f7f8fc] px-5"><Card className="max-w-md rounded-3xl text-center"><CardContent className="p-8"><BookOpen className="mx-auto h-10 w-10 text-[#3155d8]" /><h1 className="mt-4 text-2xl font-extrabold">Minhas redações</h1><p className="mt-3 text-sm leading-6 text-[#66708a]">Entre para acessar suas redações e correções salvas.</p><AuthDialog user={authUser} onUserChange={setAuthUser} triggerLabel="Entrar ou criar conta" triggerClassName="mt-6 h-11 rounded-xl bg-[#3155d8] text-white hover:bg-[#2546c3] hover:text-white" /></CardContent></Card></main>;
  return <main className="min-h-screen bg-[#f7f8fc] px-5 py-8 text-[#17233d] sm:py-12"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/painel"><span className="flex items-center gap-2 text-sm font-semibold text-[#66708a] hover:text-[#3155d8]"><ArrowLeft className="h-4 w-4" />Voltar ao painel</span></Link><h1 className="mt-5 text-3xl font-extrabold tracking-tight">Minhas redações</h1><p className="mt-2 text-sm text-[#66708a]">Acompanhe cada tentativa e reveja o feedback recebido.</p></div><AuthDialog user={authUser} onUserChange={setAuthUser} /></header><div className="mt-8 flex flex-wrap gap-2"><Filter className="mr-1 h-4 w-4 self-center text-[#7d88a0]" />{[{ key: "recent", label: "Mais recentes" }, { key: "highest", label: "Maior nota" }, { key: "lowest", label: "Menor nota" }, { key: "oldest", label: "Mais antigas" }].map(option => <button key={option.key} onClick={() => setFilter(option.key as typeof filter)} className={`rounded-full px-4 py-2 text-xs font-bold transition ${filter === option.key ? "bg-[#3155d8] text-white" : "bg-white text-[#66708a] ring-1 ring-[#e2e6f0] hover:text-[#3155d8]"}`}>{option.label}</button>)}</div>{items.length === 0 ? <Card className="mt-8 border-[#dfe5ff] bg-[#f7f9ff]"><CardContent className="p-8"><h2 className="text-xl font-extrabold">Você ainda não tem redações salvas.</h2><p className="mt-2 text-sm text-[#66708a]">Envie sua primeira redação para começar seu histórico.</p><Link href="/"><Button className="mt-5 rounded-xl bg-[#3155d8]">Nova redação <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></CardContent></Card> : <div className="mt-8 grid gap-4 md:grid-cols-2">{items.map((item, index) => <Card key={item.id} className="border-[#e7eaf2] shadow-sm"><CardHeader className="pb-3"><div className="flex items-center justify-between gap-3"><CardTitle className="text-base">Redação #{items.length - index}</CardTitle><span className="text-2xl font-extrabold text-[#3155d8]">{item.final_score}<small className="ml-1 text-xs font-medium text-[#9ba3b5]">/1000</small></span></div></CardHeader><CardContent><div className="flex items-center gap-2 text-xs font-semibold text-[#7d88a0]"><CalendarDays className="h-3.5 w-3.5" />{new Date(item.created_at).toLocaleDateString("pt-BR")} · {item.source_type === "image" ? "Imagem" : "Texto"}</div><p className="mt-3 line-clamp-3 text-sm leading-6 text-[#59657f]">{item.original_text || "Redação enviada por imagem. Consulte a correção para ver a transcrição."}</p><Link href="/"><Button variant="outline" className="mt-4 rounded-xl border-[#dfe4ef] text-[#3155d8]">Ver correção <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></CardContent></Card>)}</div>}</div></main>;
}
