import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, BarChart3, TrendingUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import AuthDialog from "@/components/AuthDialog";
import { supabase } from "@/lib/supabase";
import { trpc } from "@/lib/trpc";

type HistoryItem = { result: unknown };
type ResultShape = { competencies?: Array<{ score?: number }> };
const names = ["C1 · Norma culta", "C2 · Tema e repertório", "C3 · Argumentação", "C4 · Coesão", "C5 · Intervenção"];

export default function Performance() {
  const [authUser, setAuthUser] = useState<import("@supabase/supabase-js").User | null>(null);
  const historyQuery = trpc.correction.history.useQuery(undefined, { enabled: Boolean(authUser), retry: false });
  useEffect(() => { if (!supabase) return; void supabase.auth.getUser().then(({ data }) => setAuthUser(data.user)); }, []);
  const data = useMemo(() => names.map((name, index) => { const values = (historyQuery.data as HistoryItem[] | undefined ?? []).map(item => (item.result as ResultShape | null)?.competencies?.[index]?.score ?? 0).filter(Boolean); return { name, media: values.length ? Math.round(values.reduce((sum, value) => sum + value, 0) / values.length) : 0, primeiro: values[0] ?? 0, ultimo: values.at(-1) ?? 0 }; }), [historyQuery.data]);
  const growth = data.map(item => ({ ...item, delta: item.ultimo - item.primeiro })).sort((a, b) => b.delta - a.delta);
  if (!authUser) return <main className="flex min-h-screen items-center justify-center bg-[#f7f8fc] px-5"><Card className="max-w-md rounded-3xl text-center"><CardContent className="p-8"><BarChart3 className="mx-auto h-10 w-10 text-[#3155d8]" /><h1 className="mt-4 text-2xl font-extrabold">Meu desempenho</h1><p className="mt-3 text-sm leading-6 text-[#66708a]">Entre para acompanhar seu crescimento em cada competência.</p><AuthDialog user={authUser} onUserChange={setAuthUser} triggerLabel="Entrar ou criar conta" triggerClassName="mt-6 h-11 rounded-xl bg-[#3155d8] text-white hover:bg-[#2546c3] hover:text-white" /></CardContent></Card></main>;
  return <main className="min-h-screen bg-[#f7f8fc] px-5 py-8 text-[#17233d] sm:py-12"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/painel"><span className="flex items-center gap-2 text-sm font-semibold text-[#66708a] hover:text-[#3155d8]"><ArrowLeft className="h-4 w-4" />Voltar ao painel</span></Link><h1 className="mt-5 text-3xl font-extrabold tracking-tight">Meu desempenho</h1><p className="mt-2 text-sm text-[#66708a]">Entenda como cada competência evolui ao longo das suas redações.</p></div><AuthDialog user={authUser} onUserChange={setAuthUser} /></header>{!historyQuery.data?.length ? <Card className="mt-8"><CardContent className="p-8 text-sm text-[#66708a]">Faça uma redação para começar a acompanhar seu desempenho.</CardContent></Card> : <><Card className="mt-8 border-[#e7eaf2] shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><BarChart3 className="h-5 w-5 text-[#3155d8]" />Média por competência</CardTitle></CardHeader><CardContent><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ left: -12, right: 8 }}><CartesianGrid strokeDasharray="3 3" stroke="#e8ebf3" vertical={false} /><XAxis dataKey="name" tick={{ fontSize: 11 }} interval={0} angle={-12} textAnchor="end" height={55} /><YAxis domain={[0, 200]} tick={{ fontSize: 11 }} /><Tooltip formatter={(value: number) => [`${value}/200`, "Média"]} /><Bar dataKey="media" fill="#3155d8" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></CardContent></Card><section className="mt-5 grid gap-5 md:grid-cols-2"><Card className="border-[#dcefe2] bg-[#f4fbf7]"><CardContent className="p-6"><div className="flex items-center gap-2 text-[#24734a]"><TrendingUp className="h-5 w-5" /><span className="text-xs font-bold uppercase tracking-wider">Maior crescimento</span></div><h2 className="mt-3 text-xl font-extrabold">{growth[0]?.name ?? "Aguardando dados"}</h2><p className="mt-2 text-sm leading-6 text-[#4e6c5a]">{growth[0]?.delta > 0 ? `Seu maior crescimento foi de +${growth[0].delta} pontos desde a primeira redação.` : "Faça novas redações para identificar seu maior crescimento."}</p></CardContent></Card><Card className="border-[#dfe5ff] bg-[#f7f9ff]"><CardContent className="p-6"><div className="flex items-center gap-2 text-[#3155d8]"><BarChart3 className="h-5 w-5" /><span className="text-xs font-bold uppercase tracking-wider">Oportunidade atual</span></div><h2 className="mt-3 text-xl font-extrabold">{growth.at(-1)?.name ?? "Aguardando dados"}</h2><p className="mt-2 text-sm leading-6 text-[#66708a]">Essa é a competência que merece mais atenção no próximo treino.</p></CardContent></Card></section></>}</div></main>;
}
