import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, CheckCircle2, Target } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import AuthDialog from "@/components/AuthDialog";
import { supabase } from "@/lib/supabase";
import { trpc } from "@/lib/trpc";

const names = ["Norma culta", "Tema e repertório", "Argumentação", "Coesão", "Intervenção"];
export default function Plan() {
  const [authUser, setAuthUser] = useState<import("@supabase/supabase-js").User | null>(null);
  const [goal, setGoal] = useState(() => Number(localStorage.getItem("aprovai-goal") || 900));
  const historyQuery = trpc.correction.history.useQuery(undefined, { enabled: Boolean(authUser), retry: false });
  useEffect(() => { if (!supabase) return; void supabase.auth.getUser().then(({ data }) => setAuthUser(data.user)); }, []);
  const current = historyQuery.data?.[0]?.final_score ?? 0;
  const weakest = useMemo(() => { const sums = [0, 0, 0, 0, 0]; const counts = [0, 0, 0, 0, 0]; for (const entry of historyQuery.data ?? []) { const competencies = (entry.result as { competencies?: Array<{ score?: number }> } | null)?.competencies ?? []; competencies.forEach((item, index) => { if (item.score) { sums[index] += item.score; counts[index] += 1; } }); } return sums.map((sum, index) => ({ index, value: counts[index] ? sum / counts[index] : 0 })).sort((a, b) => a.value - b.value)[0]?.index ?? 2; }, [historyQuery.data]);
  if (!authUser) return <main className="flex min-h-screen items-center justify-center bg-[#f7f8fc] px-5"><Card className="max-w-md rounded-3xl text-center"><CardContent className="p-8"><Target className="mx-auto h-10 w-10 text-[#3155d8]" /><h1 className="mt-4 text-2xl font-extrabold">Seu plano de evolução</h1><p className="mt-3 text-sm leading-6 text-[#66708a]">Entre para transformar seu histórico em um plano de treino.</p><AuthDialog user={authUser} onUserChange={setAuthUser} triggerLabel="Entrar ou criar conta" triggerClassName="mt-6 h-11 rounded-xl bg-[#3155d8] text-white hover:bg-[#2546c3] hover:text-white" /></CardContent></Card></main>;
  const saveGoal = () => { localStorage.setItem("aprovai-goal", String(goal)); };
  const weeks = [`Diagnosticar e treinar ${names[weakest].toLowerCase()}.`, "Reescrever um parágrafo de desenvolvimento com mais profundidade.", "Aplicar repertório pertinente e conectá-lo diretamente à tese.", "Produzir uma redação completa e comparar sua evolução."];
  return <main className="min-h-screen bg-[#f7f8fc] px-5 py-8 text-[#17233d] sm:py-12"><div className="mx-auto max-w-5xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/painel"><span className="flex items-center gap-2 text-sm font-semibold text-[#66708a] hover:text-[#3155d8]"><ArrowLeft className="h-4 w-4" />Voltar ao painel</span></Link><h1 className="mt-5 text-3xl font-extrabold">Seu Plano de Evolução</h1><p className="mt-2 text-sm text-[#66708a]">Um próximo passo claro para você escrever melhor.</p></div><AuthDialog user={authUser} onUserChange={setAuthUser} /></header><section className="mt-8 grid gap-5 md:grid-cols-3"><Card className="border-[#dfe5ff] bg-[#f7f9ff]"><CardContent className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-[#3155d8]">Meta do aluno</p><div className="mt-3 flex items-center gap-2"><Input type="number" min="0" max="1000" value={goal} onChange={event => setGoal(Number(event.target.value))} className="h-11 w-28 rounded-xl bg-white text-xl font-bold" /><Button onClick={saveGoal} className="rounded-xl bg-[#3155d8]">Salvar</Button></div></CardContent></Card><Card><CardContent className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-[#7b849a]">Nota atual</p><p className="mt-3 text-3xl font-extrabold">{current}<small className="ml-1 text-xs font-medium text-[#9ba3b5]">/1000</small></p></CardContent></Card><Card><CardContent className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-[#7b849a]">Distância</p><p className="mt-3 text-3xl font-extrabold text-[#3155d8]">{Math.max(goal - current, 0)}<small className="ml-1 text-xs font-medium text-[#9ba3b5]">pontos</small></p></CardContent></Card></section><Card className="mt-5 border-[#e7eaf2] shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><Target className="h-5 w-5 text-[#3155d8]" />Plano de 4 semanas</CardTitle><p className="text-sm text-[#66708a]">A competência que merece atenção agora é <strong>{names[weakest]}</strong>.</p></CardHeader><CardContent className="grid gap-3 md:grid-cols-4">{weeks.map((week, index) => <div key={week} className="rounded-2xl bg-[#f7f8fc] p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#3155d8]">Semana {index + 1}</p><CheckCircle2 className="mt-4 h-5 w-5 text-[#7e91df]" /><p className="mt-3 text-sm font-semibold leading-6 text-[#4e5a73]">{week}</p></div>)}</CardContent></Card></div></main>;
}
